### ISSUE TITLE
Taking over ownership

### ISSUE THREAD

**Issue by vdhpieter** [kvaps/docker-letsencrypt-webroot#11]
Hello,

I use this project for my own project and loved how easy the setup was. It just worked and that was awesome.

I got a notification from Let's Encrypt that I was using an old method to verify my ownership so I looked into it and figured the base image used in this repo was outdated. I also noticed the part in the readme where you said that you were looking for someone to take over.

I did a lot of trial and error but I got it to work again with the new certbot image (I was not used to Alpine Linux)
Repo: https://github.com/vdhpieter/docker-letsencrypt-webroot
DockerHub: https://hub.docker.com/r/vdhpieter/letsencrypt-webroot/

I have not much experience with open source but it seems this relatively small project is maybe a good way to get started. If it's ok for you I would be open to take over and try to support this project, look at feature requests and fix bugs.

Kind regards,
Pieter

**Comment by kvaps** [comment]
Hi, awesome, I'd like to add notice about the project deprecation with the link on your fork if you don't mind.
Later this project will be archived

**Comment by kvaps** [comment]
Job is done!
Thank you for being interested in the development of this small project and good luck in your endeavors :)

**Comment by vdhpieter** [comment]
Thanks for the confidence!
