### ISSUE TITLE
uid and guid inside docker volumes

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [kvaps/docker-letsencrypt-webroot#2]
Hi kvaps,

i think the some some problems are involved by the way how chown is used. As i understand, the CHOWN environment variable should be used, when the certs owner should be a custom owner. I think it is designated to use the chown environment variable to switch the certs ownership to those user:group for those running in an webserver container. So for example the ’mail’ group is advisable for the kvaps/kolab container.

The problem which i see here is that the uid and guid is not aligned between two independent containers. So setting the ’mail’ group determines another gid in the letsencrypt container compared to the kolab container. When the system is the same and the users and groups are added in the same order, the ids should be aligned. Otherwise it is a coincidence that those ids are aligned.

It is the same problem, which is discussed for the data-only container pattern.
http://container42.com/2014/11/18/data-only-container-madness/
http://jdemarks.azurewebsites.net/2015/04/1083/

As i see in the discussion, there are two possible ways to go.
1. make sure that the uid and guid matches between the data and service container (here e.g. the kolab and letsencrypt). In my eyes this is a problem, because an additional dependency for the letsencrypt container is introduced, which makes it less flexible to combine with other containers.
2. Initialize the ownership at startup of the service container (here e.g. kolab runs the chown during startup). In my eyes it seems to be more flexible in terms of the combination of letsencrypt with other containers.

My suggestion for this exact situation (based on solution 2):
I think the most clean way would be to integrate this chown directly into the renew hook. The hook should trigger the chown command of the service container using the certs (e.g. kolab). But i don't know how to handle in a nice way those hooks. Do you see a way to implement this?

I am looking forward to a nice discussion :)

best,
Christian

**Comment by kvaps** [comment]
Hi Cristian,

Yes, there is the problem and is now being. The similar problem [actively discussed](https://github.com/docker/docker/issues/7198) in the official docker github repo.

Letsencrypt-webroot image was developed as an independent way that it could be used with any other image, not only  with kolab.

Please use the numerical values UID and GID from your image.
I believe that until separate standard will not appear for this, no sense to solve the problem in some other way.

Thanks for understanding!

ps: In the near future I want to make an image that will use hooks to perform any commands requested for any containers.
With this you can execute any additional commands by simply adding a special environment variable for your container and link to this image.

**Comment by cguentherTUChemnitz** [comment]
Very nice to point out the official docker github discussion. In this case i totally agree with you that using the specific IDs of the service container is a sufficient solution for now. Additional steps should be postponed until the official development has finished the uid/guid handling.

Thanks!
