### ISSUE TITLE
DOMAINS not working

### ISSUE THREAD

**Issue by R0GGER** [kvaps/docker-letsencrypt-webroot#3]
Something weird... `-e 'DOMAINS=example.com www.example.com'` is not working.
It's only creating certificates for the first domain...

**Comment by kvaps** [comment]
Hi, this image gets or update only one certificate per running container, but for all domains listed in DOMAINS variable.

You can check it by `docker logs` command, or check domains listed on the received certificate.

``` bash
cat conf/live/example.com/cert.pem | openssl x509 -text -noout | grep -oP '(?<=DNS:)[^,]*'
```
