### ISSUE TITLE
Does not work any more, parent container renamed letsencrypt to certbot

### ISSUE THREAD

**Issue by raarts** [kvaps/docker-letsencrypt-webroot#4]
/bin/start.sh: line 61: letsencrypt: command not found

**Comment by kvaps** [comment]
Hi, I took corrections from @aohorodnyk's code.
This is nice code.
Thanks!

**Comment by kvaps** [comment]
It seems I am too hurried and not properly checked this code .
Currently I revert pull request #5, and took your corrections.
@raarts Thanks again! And sorry for confusion.
