### ISSUE TITLE
nginx won't start with out keys

### ISSUE THREAD

**Issue by chrishoage** [kvaps/docker-letsencrypt-webroot#6]
I've run into a chicken and egg problem: My nginx config references the paths to the letsencrypt keys, which won't exist first run. 

This prevents the service from starting and allowing certbot to connect and auth the domain. 

My solution for the moment was to comment out the entire ssl server block, let it do its thing, then bring down the containers and re-enable the ssl server block. 

This worked! But is pretty painful, I'm curious if you have a more elegant solution? 

(Excellent work, this is super simple and easy)

**Comment by kvaps** [comment]
Yes I know your problem,
I think I will add generating self-signed certificate before for make nginx working with ssl section.

**Comment by kvaps** [comment]
Probably fixed, thanks @Manuel-S
