### ISSUE TITLE
Versioned docker images

### ISSUE THREAD

**Issue by jaapz** [kvaps/docker-letsencrypt-webroot#7]
Could you maybe tag a versioned docker image?
This image is really great and works well but I don't really like relying on "latest" tags in production :)

**Comment by kvaps** [comment]
Yes, good idea, I will think about it some bit later.

**Comment by Dineshs91** [comment]
@kvaps Any progress with this issue ? I can help with this. Versioning really helps when using this in production. I like this image a lot, but I am unable to use in production, because of the versions not being available.

**Comment by vdhpieter** [comment]
@Dineshs91 This is the case in the new version of this project: https://github.com/vdhpieter/docker-letsencrypt-webroot currently at v1.0.0 😄Let me know if I can help with anything else!
